name: linux-build

on:
  pull_request:
  push:
    branches:
      - main
      - master
    paths-ignore:
      - '**/README.md'
      - '.github/workflows/macos-*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04
    env:
      MIX_ENV: test
      CVT_COLOR_BUILD_BENCHMARK: ON

    steps:
      - uses: actions/checkout@v2
      
      - uses: erlef/setup-beam@v1
        with:
          otp-version: 24.1.5
          elixir-version: 1.12.3
      
      - name: Install system dependecies
        run: sudo apt-get update && sudo apt-get install -y build-essential automake autoconf pkg-config bc m4 curl git libssl-dev libncurses5-dev erlang-runtime-tools erlang-ssl erlang-dev ca-certificates

      - name: Get Elixir Dependencies
        run: mix deps.get

      - name: Compile Elixir Dependencies
        run: mix deps.compile

      - name: Compile
        run: mix compile

      - name: Benchmark (C++)
        run: |
          # min_chunk_size: 64 KB
          _build/test/lib/cvt_color/cmake/cvt_color_benchmark 65536
          # min_chunk_size: 256 KB
          _build/test/lib/cvt_color/cmake/cvt_color_benchmark 262144
          # min_chunk_size: 1 MB
          _build/test/lib/cvt_color/cmake/cvt_color_benchmark 1048576
