name: macos-build

on:
  pull_request:
  push:
    branches:
      - main
      - master
    paths-ignore:
      - '**/README.md'
      - '.github/workflows/linux-*'
  workflow_dispatch:

jobs:
  mix_test:
    runs-on: macos-11
    env:
      MIX_ENV: test

    steps:
      - uses: actions/checkout@v2
      
      - name: Install Erlang and Elixir
        run: |
          brew install erlang elixir libomp
          mix local.hex --force
          mix local.rebar --force
      - name: Get Elixir Dependencies
        run: mix deps.get

      - name: Compile Elixir Dependencies
        run: mix deps.compile

      - name: Compile
        run: mix compile

      - name: Benchmark (C++)
        run: |
          # min_chunk_size: 64 KB
          _build/test/lib/cvt_color/cmake/cvt_color_benchmark 65536
          # min_chunk_size: 256 KB
          _build/test/lib/cvt_color/cmake/cvt_color_benchmark 262144
          # min_chunk_size: 1 MB
          _build/test/lib/cvt_color/cmake/cvt_color_benchmark 1048576
